### ISSUE TITLE
ServerModels.cs is NOT packed with your Unity Asset Package on your website!

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/UnitySDK#100]
https://github.com/PlayFab/UnitySDK/blob/f0a5b1261fa052df212d1c077a0f6f000fd0e8ae/PlayFabCombinedTestingSample/Assets/PlayFabSDK/Public/PlayFabServerModels.cs 

^ Missing from your website's package; had to hunt it down

I informed CS, but not sure how long it'll take to fix, so better everyone knows until then.

**Comment by pgilmorepf** [comment]
The unity asset package is a client-only collection, and is named to support that statement:
https://github.com/PlayFab/UnitySDK/blob/master/PlayFabClientSDK.unitypackage

You should not use the client unity package for your server executable.  You will need to manually copy files from the PlayFabServerSample.
https://github.com/PlayFab/UnitySDK/tree/master/PlayFabServerSample/Assets
