### ISSUE TITLE
PlayFabServerAPI also missing from Unity asset package from the website

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/UnitySDK#101]
Another entire file missing:

https://api.playfab.com/docs/using-player-data @ public void UpdateUserReadOnlyData()

You are missing the PlayFabServerAPI file, resulting in a syntax error / class not found.

This is found @ https://github.com/PlayFab/UnitySDK/blob/f0a5b1261fa052df212d1c077a0f6f000fd0e8ae/PlayFabCombinedTestingSample/Assets/PlayFabSDK/Public/PlayFabServerAPI.cs 

This is also not packaged in your website's asset package. It seems that anything to do with Server classes rather than Client is all missing, actually.

Like the last bug report, it seems so far so good when I manually place it in the playfab/public/ folder in Unity and rebuild.

**Comment by pgilmorepf** [comment]
The unity asset package is a client-only collection:
https://github.com/PlayFab/UnitySDK/blob/master/PlayFabClientSDK.unitypackage

You should not use the client unity package for your server executable.  You will need to manually copy files from the PlayFabServerSample.
https://github.com/PlayFab/UnitySDK/tree/master/PlayFabServerSample/Assets
