### ISSUE TITLE
DeveloperSecretKey not defined in PlayFabSettings

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/UnitySDK#102]
About 140 references to a "DeveloperSecretKey" not found in **PlayFabSettings** class, requested from **PlayFabServerAPI** class

**Comment by pgilmorepf** [comment]
I suspect you have an improper mix of files from PlayFabClientSample and PlayFabServerSample.

As you can see, DeveloperSecretKey exists in both of these files:
https://github.com/PlayFab/UnitySDK/blob/master/PlayFabServerSample/Assets/PlayFabSDK/Public/PlayFabSettings.cs
https://github.com/PlayFab/UnitySDK/blob/master/PlayFabCombinedTestingSample/Assets/PlayFabSDK/Public/PlayFabSettings.cs

and does not exist here:
https://github.com/PlayFab/UnitySDK/blob/master/PlayFabClientSample/Assets/PlayFabSDK/Public/PlayFabSettings.cs

You need to make sure you don't mix your sdk files from one folder to another, as they're built specifically for that folder.
