### ISSUE TITLE
Assets/PlayFabSDK/Internal/PlayFabHTTP.cs(46,33): error CS0019: Operator `==' cannot be applied to operands of type `PlayFab.WebRequestType' and `PlayFab.Internal.WebRequestType'

### ISSUE THREAD

**Issue by abdojapan** [PlayFab/UnitySDK#141]
Hi,

I have a game source that uses the Admin and Client APIs. So I got the combined stuff from here.
[Playfab Combined](https://github.com/PlayFab/UnitySDK/tree/master/PlayFabCombinedTestingSample/Assets/PlayFabSDK/Public)

But now I am getting this error.

> Assets/PlayFabSDK/Internal/PlayFabHTTP.cs(46,33): error CS0019: Operator `==' cannot be applied to operands of type `PlayFab.WebRequestType' and `PlayFab.Internal.WebRequestType'

Even when I try to resolve it manually, I get tons of similar issues of conflict between 'PlayFab' and 'PlayFab.Internal' namespaces.

Any help is greatly appreciated.

**Comment by pgilmorepf** [comment]
I believe you have tried to update your SDK by pasting a new version over-top of an old version.
Please delete this folder: {YourProject}/Assets/PlayFabSdk/
And then download and copy a fresh PlayFabSdk folder into your project.
If this folder exists: {YourProject}/Assets/Plugins/PlayFabShared, then you are trying to combine the client sdk and combined sdk in a way that is not intended.  You should not use any client-sdk plugins with the combined sdk.

I'm going to close this issue, so if you continue to have issues, the best place to get help is on our forums:
https://community.playfab.com/index.html

This location is for issues with the SDK itself.  The forum is better for troubleshooting issues specifically with your project.

**Comment by pgilmorepf** [comment]
Clarified when you should use the forums vs issues after some internal discussion.  :smile:
