### ISSUE TITLE
CallRequestContainer missing

### ISSUE THREAD

**Issue by redsend** [PlayFab/UnitySDK#148]
Just imported the last unitySDK and I got this error, maybe some missing script in the package. I deleted manually the previous version and after imported the new one.

Assets/Plugins/PlayFabShared/PlayFabPluginEventHandler.cs(10,49): error CS0246: The type or namespace name `CallRequestContainer' could not be found. Are you missing a using directive or an assembly reference?

Assets/Plugins/PlayFabShared/PlayFabPluginEventHandler.cs(50,44): error CS0246: The type or namespace name `CallRequestContainer' could not be found. Are you missing a using directive or an assembly reference?

**Comment by MarcoWilliamsPF** [comment]
This is because you imported over the existing (previous version of the SDK) .. I will be writting up a proper upgrade guide today.  Until then the resolution is to remove the SDK completely and import fresh.
