### ISSUE TITLE
LoginResult conflict with Facebook SDK

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnitySDK#149]
[PlayFabClientModels.LoginResult](https://github.com/PlayFab/UnitySDKV2Beta/blob/master/Source/PlayFabSDK/Client/PlayFabClientModels.cs#L2692) can be confused with facebook's [LoginResult](https://github.com/facebook/facebook-sdk-for-unity/blob/master/Facebook.Unity/Assets/FacebookSDK/SDK/Scripts/Results/LoginResult.cs).

**Comment by MarcoWilliamsPF** [comment]
Since we have ours namespace'd and Facebook also has theirs namespace'd there should not be any conflict unless you are using both  PlayFab.ClientModels & Facebook.Unity  in the same file, in which case you will have to explicitly specify the type on that class in the handler.
