### ISSUE TITLE
RegisterPlayFabUser throws NullReference

### ISSUE THREAD

**Issue by jrDev1** [PlayFab/UnitySDK#155]
Line 117 of PlayFabWWW.cs with this code:
userSettings = res.SettingsForUser;

throws error.

NullReferenceException: Object reference not set to an instance of an object
PlayFab.Internal.PlayFabWWW+<MakeApiCall>c__AnonStorey16`2[PlayFab.ClientModels.RegisterPlayFabUserRequest,PlayFab.ClientModels.RegisterPlayFabUserResult].<>m__164 (System.String response) (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabWWW.cs:118)
UnityEngine.Debug:LogException(Exception)
PlayFab.Internal.<MakeApiCall>c__AnonStorey16`2:<>m__164(String) (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabWWW.cs:210)
PlayFab.Internal.<Post>c__IteratorB:MoveNext() (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabWWW.cs:260)

Even after the error, though, the player still gets registered.

**Comment by pgilmorepf** [comment]
This has already been fixed internally, and will be published in the next build.
As you can see it has already been built to the automated testing branch:
https://github.com/PlayFab/UnitySDK/blob/nightly/Source/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabWWW.cs#L117

If you like checking "beta" builds, then you can check out our public nightly branch at any time.  Builds posted to this branch have passed our internal automated testing, but may not yet be testing new and specific issues.  As well as it can contain code that's not officially released yet.

The next build will probably be updated Monday July 25th, along with additional fixes to Windows Phone, Unity 4.7, and others.

Sorry for the delay, thanks for your patience.

**Comment by pgilmorepf** [comment]
Fix posted early:
https://api.playfab.com/releaseNotes/#160721
