### ISSUE TITLE
PlayFabHttp Null Again

### ISSUE THREAD

**Issue by jrDev1** [PlayFab/UnitySDK#156]
I mentioned an error like this before about line 117, still give null error:
_internalHttp.DevKey = PlayFabSettings.DeveloperSecretKey ?? _internalHttp.DevKey;

NullReferenceException: Object reference not set to an instance of an object
PlayFab.Internal.PlayFabHttp.Awake () (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:117)
UnityEngine.GameObject:AddComponent()
PlayFab.Internal.SingletonMonoBehaviour`1:CreateInstance() (at Assets/PlayFabSDK/Shared/Internal/SingletonMonoBehaviour.cs:32)
PlayFab.Internal.PlayFabHttp:InitializeHttp() (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:75)
PlayFab.Internal.PlayFabHttp:MakeApiCall(String, String, RegisterPlayFabUserRequest, String, Action`1, Action`1, Object) (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:106)
PlayFab.PlayFabClientAPI:RegisterPlayFabUser(RegisterPlayFabUserRequest, Action`1, Action`1, Object) (at Assets/PlayFabSDK/Client/PlayFabClientAPI.cs:163)

**Comment by pgilmorepf** [comment]
Which version of Unity are you using?

**Comment by pgilmorepf** [comment]
We have a fix for this.  It'll be published Monday July 25, 2016.
Stay tuned.
