### ISSUE TITLE
Build fails on iOS

### ISSUE THREAD

**Issue by MaurGi** [PlayFab/UnitySDK#164]
Assets/PlayFabSdk/Client/PlayFabIdfa.cs(37,47): error CS0246: The type or namespace name `AttributeInstallResult' could not be found. Are you missing a using directive or an assembly reference?

**Comment by pgilmorepf** [comment]
Thanks for the report.
The HotFix for this will be pushed later tonight.

**Comment by MaurGi** [comment]
Thanks for the quick fix!
