### ISSUE TITLE
API calls fail on the WebPlayer target for Unity 4.5

### ISSUE THREAD

**Issue by nulldatamap** [PlayFab/UnitySDK#167]
Due to sandbox constraints in the WebPlayer target platform for older versions of Unity, certain headers are not allowed to be set by scripts. Resulting in the following errors when trying to use the API:
```
ArgumentException: Cannot overwrite header: Accept-Encoding
UnityEngine.WWW.CheckSecurityOnHeaders (System.String[] headers) (at C:/BuildAgent/work/d63dfc6385190b60/Runtime/Export/WWW.cs:71)
UnityEngine.WWW..ctor (System.String url, System.Byte[] postData, System.Collections.Generic.Dictionary`2 headers) (at C:/BuildAgent/work/d63dfc6385190b60/artifacts/EditorGenerated/Utils.cs:88)
PlayFab.Internal.PlayFabWww.MakeApiCall (PlayFab.Internal.CallRequestContainer reqContainer) (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabWWW.cs:59)
PlayFab.Internal.PlayFabHttp.MakeApiCall[GetAccountInfoResult] (System.String apiEndpoint, PlayFab.SharedModels.PlayFabRequestCommon request, AuthType authType, System.Action`1 resultCallback, System.Action`1 errorCallback, System.Object customData) (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:141)
<...>

```

**Comment by pgilmorepf** [comment]
Like Unity, we don't fully support Unity 4.
Our internal testing ensures that Unity 4.7.2 is stable, but it doesn't support all platforms or features.
Specifically, windows phone platform and push notifications aren't currently working in 4.7, but we hope to restore those, eventually.  We won't be testing or fixing older Unity versions.

If you can, please upgrade to Unity 4.7.2, and re-test, and let us know if you have errors.
