### ISSUE TITLE
API calls fail on the WebPlayer target for Unity 4.7

### ISSUE THREAD

**Issue by nulldatamap** [PlayFab/UnitySDK#172]
Same issue as #167 except we upgraded to Unity 4.7.2. 
From issue #167:
Due to sandbox constraints in the WebPlayer target platform for older versions of Unity, certain headers are not allowed to be set by scripts. Resulting in the following errors when trying to use the API:
```
ArgumentException: Cannot overwrite header: Accept-Encoding
UnityEngine.WWW.CheckSecurityOnHeaders (System.String[] headers) (at C:/BuildAgent/work/d63dfc6385190b60/Runtime/Export/WWW.cs:71)
UnityEngine.WWW..ctor (System.String url, System.Byte[] postData, System.Collections.Generic.Dictionary`2 headers) (at C:/BuildAgent/work/d63dfc6385190b60/artifacts/EditorGenerated/Utils.cs:88)
PlayFab.Internal.PlayFabWww.MakeApiCall (PlayFab.Internal.CallRequestContainer reqContainer) (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabWWW.cs:59)
PlayFab.Internal.PlayFabHttp.MakeApiCall[GetAccountInfoResult] (System.String apiEndpoint, PlayFab.SharedModels.PlayFabRequestCommon request, AuthType authType, System.Action`1 resultCallback, System.Action`1 errorCallback, System.Object customData) (at Assets/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:141)
<...>

```

**Comment by pgilmorepf** [comment]
I believe we've already solved this, but the solution has not yet been published.
There should be a very simple change which you can make to resolve the issue:
In Unity, find the scriptableObject at this location:
{Project}/Assets/PlayFabSdk/Shared/Public/Resources/PlayFabSharedSettings.asset
Uncheck the "Compress Api Data" option.

This will disable the code referenced in the error you're getting.
Once we release the next PlayFab Sdk (UnitySdk 2.5.xxxxxx), then the  real fix should be in place.  After that, you can re-enable compression for non-web builds.

Please let us know if disabling compression fixes the issue for you.

**Comment by nulldatamap** [comment]
Disabling compression does fix it.

**Comment by pgilmorepf** [comment]
Great!
So, later today, we'll push a build which automatically disables compression for WebGL, which I believe will solve your issue completely.
I'm closing this issue since you are taken care of, and we've addressed this issue properly in the next build.
