### ISSUE TITLE
[Android plugin:PlayServicesUtils] null pointer exception causes app to crash

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnitySDK#184]
[PlayServicesUtils line 28](https://github.com/PlayFab/UnitySDK/blob/master/PluginsSource/UnityAndroidPluginSource/playfabunityplugin/src/main/java/com/playfab/unityplugin/GCM/PlayServicesUtils.java#L28).
[crash report](http://crashes.to/s/20307bd8f3f)

**Comment by MarcoWilliamsPF** [comment]
@JohnTube   We have released new .AAR files for the Push Plugin.  Please let me know if this resolved your issue.

**Comment by JohnTube** [comment]
This issue is still there with the new plugin version.

**Comment by JohnTube** [comment]
FYI: @pgilmorepf
