### ISSUE TITLE
[Android plugin:NotificationPublisher] null pointer exception causes app to crash

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnitySDK#185]
[NotificationPublisher line 24.](https://github.com/PlayFab/UnitySDK/blob/master/PluginsSource/UnityAndroidPluginSource/playfabunityplugin/src/main/java/com/playfab/unityplugin/GCM/NotificationPublisher.java#L24)
[crash report](http://crashes.to/s/5170eb60d4b)

**Comment by MarcoWilliamsPF** [comment]
@JohnTube   Can you provide more information on steps to reproduce this.  I cannot repo this issue on any device.   I don't recognize the device that you are specifically testing with here,  but when I looked it up on google it says it is running Android 6.0.  Which should work just fine.  So I need to identify the steps in which you've encountered this error for me to resolve.

**Comment by MarcoWilliamsPF** [comment]
@JohnTube  .. Never mind,  I found the issue.  I have a fix that I am working on and should have the fix submitted within the next couple days

**Comment by MarcoWilliamsPF** [comment]
This is fixed,  pull the latest android plugin and the problem should be resolved.
