### ISSUE TITLE
Problem with Local ScheduleNotification

### ISSUE THREAD

**Issue by pradeepkulasekaran** [PlayFab/UnitySDK#186]
```
string notificationJson;

// calling the below line in start after login.
var senderId = player.playerID; //put your sender id here.
PlayFabAndroidPlugin.Init(senderId);

// Getting sender id from player after he login using google play services.
public void SetNotification()
	{
		var sDate = DateTime.Now.AddMinutes(1);
		outputText.text = "clicked";
		PlayFabNotificationPackage ScheduledNotification = new PlayFabNotificationPackage()
		{
			ScheduleType = ScheduleTypes.ScheduledDate,
			Message = "testing notification",
			Title = "spin",
			Id = "SpinWheel",
			ScheduleDate = sDate
		};
		notificationJson = PlayFab.Json.JsonWrapper.SerializeObject(ScheduledNotification);
		
		PlayFabAndroidPlugin.ScheduleNotification(notificationJson, sDate);
		outputText.text = "notificationTriggered";
	}
```

Notification is triggering, but its triggering as soon as i click the button.( i have mapped the fn SetNotification to a UI Button).
There is no delay and the schedule isn't working..

**Comment by MarcoWilliamsPF** [comment]
I am fairly confident that this is because of the format of your date.   The date/time needs to be formatted in this way:

`private static final String DATE_FORMAT_STRING = "dd-M-yyyy HH:mm:ss";`

If it cannot parse the date, it automatically reverts to NOW.

**Comment by pradeepkulasekaran** [comment]
i will check on the date format.
Do sender Id refer to google project number or it can be any?
Even with the wrong format for date I am not getting any Title or Message in the push notification.
Are these related?

**Comment by pradeepkulasekaran** [comment]
Date 04/05/2017 23:44:20
UnityEngine.Debug:Log(Object)
ServerTestScript:SetNotification() (at Assets/Scripts/GManager/ServerTestScript.cs:139)
UnityEngine.EventSystems.EventSystem:Update()

This is the output i get while printing sDate.
I guess this is correct with the format u specified.
I am not getting Title, Message etc in the notification i received. 
Just the Icon.
