### ISSUE TITLE
PlayFabAndroid.cs changes

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnitySDK#191]
PlayFabAndroid.cs and PlayFabPluginEventHandler.cs files are not in the repo but are in the Unity SDK (should be part of Unity Android plugin).
In the latest Android plugin update, the platform defines were changed (probably for testing/debugging)
from
`#if UNITY_ANDROID && !UNITY_EDITOR`
to
`#if UNITY_ANDROID //&& !UNITY_EDITOR`
which throws errors in the Unity editor.

**Comment by pgilmorepf** [comment]
I can confirm the issue.
The fix is en-route.
It'll be live in the next SDK release (v2.22)
Thanks for catching this!
