### ISSUE TITLE
Wrong date format in the android local notifications

### ISSUE THREAD

**Issue by pmanzano** [PlayFab/UnitySDK#192]
In android, the local notifications scheduled to be send from 12 pm to 1pm (12:00 to 13:00) are set to launch at 00:XX.
In the `PlayFabAndroid.cs`, in the method `ScheduleNotification` is the following line:
`var dateString = date.ToString("MM-dd-yyyy HH:mm:ss");`
while in the `PlayFabNotificationPackage.java`, in the method `SetScheduleDate` the date is parsed with:
`SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy hh:mm:ss");`

The date is sent as a 24 hour format and readed as a 12 hour format. It should be `SimpleDateFormat("MM-dd-yyyy HH:mm:ss");`

**Comment by pgilmorepf** [comment]
I can confirm the issue.
The fix is en-route.
It'll be live in the next SDK release (v2.22)
Thanks for catching this!
