### ISSUE TITLE
Wrong Push Notifications Android Plugin Dependencies

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnitySDK#193]
The Android Push Notifications Plugins still uses Google Cloud Messaging but in the gradle dependencies it has duplicate ones of the old GCM (expected) and new Firebase Cloud Messaging (duplicate, should be removed).

```
compile 'com.google.android.gms:play-services-gcm:10.2.1'
compile 'com.google.firebase:firebase-messaging:10.0.1'
```
[source](https://github.com/PlayFab/UnitySDK/blob/master/PluginsSource/UnityAndroidPluginSource/playfabunityplugin/build.gradle#L27)]

And there is a version mismatch between the archives listed in [the dependencies table in the readme](https://github.com/PlayFab/UnitySDK/tree/master/PluginsSource/UnityAndroidPluginSource#7-resolving-jar--aar-conflicts) and the gradle file ("10.0.1" vs "10.2.1").

**Comment by pgilmorepf** [comment]
You're right.  If I roll back the dependency to
compile 'com.google.android.gms:play-services-gcm:10.0.1'
and remove the Firebase dependency, then everything works with no change to the Java code.
The change will be deployed in our next UnitySDK release v2.22
Thanks for reporting this!
