### ISSUE TITLE
SignalR.NET20/Properties/AssemblyInfo.cs shouldn't be included the build (maybe not even in the repo).

### ISSUE THREAD

**Issue by nlebedenco** [PlayFab/UnitySDK#203]
I think this was an oversight simply because a single AssemblyInfo.cs file in a Unity project usually goes unnoticed unless you care to verify the generated assembly in detail. And the AssemblyInfo.cs in question is even enclosed by #if ENABLE_PLAYFABPLAYSTREAM_API && ENABLE_PLAYFABSERVER_API but you can get several somewhat cryptic errors about redefinitions of assembly attributes if you happen to use those compiler directives and have more than one AssemblyInfo.cs hanging in your Assets folder. A simple solution would be to use an asmdef file to create a separate assembly for SignalR so its AssemblyInfo can be isolated and used properly. This is my approach for example with Rotorz.ReorderableList. However 
there are several references to the PlayFab namespace inside SignalR sources which prevents the creation of a separate assembly. I could separate the whole PlayFabSdk using an asmdef but then it would be using the wrong info. In fact, this AssemblyInfo doesn't even reflect the truth about SignalR since this is a customized version and not the one identified by the info.

**Comment by pgilmorepf** [comment]
Thanks for the bug report.
Yeah, I agree this is something to look into.
I will set a task to investigate as soon as we can.

**Comment by pgilmorepf** [comment]
That file will be deleted in the next build.
You can delete it locally to resolve the error you're experiencing now as well.
