### ISSUE TITLE
Add await/async support?

### ISSUE THREAD

**Issue by kamyker** [PlayFab/UnitySDK#214]
I think "UnitySynchronizationContext" was added in 2017. I've added custom GetAwaiter for ExecuteCloudScriptRequest instead of using PlayFabClientAPI.ExecuteCloudScript and so far it works (and looks) great in 2019.1.

```
public static TaskAwaiter<ExecuteCloudScriptResult>
	GetAwaiter(this ExecuteCloudScriptRequest executeCloudScriptRequest)
{
	var tcs = new TaskCompletionSource<ExecuteCloudScriptResult>();
	PlayFabClientAPI.ExecuteCloudScript(executeCloudScriptRequest,
		result => tcs.SetResult(result),
		error => tcs.SetException(new Exception(error.GenerateErrorReport())));
	return tcs.Task.GetAwaiter();
}
```
```
var result = await new ExecuteCloudScriptRequest()
{
	FunctionName = "testFunc",
	FunctionParameter =
	new { varName = varValue }
};
```

**Comment by kamyker** [comment]
Almost ended up doing custom sdk generator but instead created this ugly and slow extension method with reflections:
```
public static TaskAwaiter<object>
	GetAwaiter(this PlayFabRequestCommon request)
{
	var tcs = new TaskCompletionSource<object>();
	try
	{
		string methodName = request.GetType().Name.Replace("Request", "");
		var methodInfo = typeof(PlayFabClientAPI)
			.GetMethod(methodName, BindingFlags.Static | BindingFlags.Public);

		object[] parameters = new object[5]
		{
			request,
		(Action<PlayFabResultCommon>)
			(result => tcs.SetResult(result)),
		(Action<PlayFabError>)
			(error => tcs.SetResult(error)),
		null,
		null
		};

		methodInfo.Invoke(null, parameters);
	}
	catch (Exception e)
	{
		tcs.SetException(e);
	}

	return tcs.Task.GetAwaiter();
}
```
Usage:
```
var result = await new PurchaseItemRequest()
{
	ItemId = catalogItem.ItemId,
	Price = price,
	VirtualCurrency = "BC"
};
if (result is PlayFabError)
	Debug.Log(((PlayFabError)result).GenerateErrorReport());
else
{
	//var purchaseResult = (PurchaseItemResult)result;
	RefreshStore();
}
```
It works with pretty much everything. Maybe `error => tcs.SetException(error)` could be better. That way multiple requests could be put inside single try-catch but that would require `PlayFabError : Exception` inheritance.
Just a dirty solution until real async support.

**Comment by heshuimu** [comment]
I wanted to use async/await in my project as well, and I ended up using the C# SDK rather than the Unity SDK. It seems to work in editor (with .NET Standard 2.0 enabled) which should also work on IL2CPP builds. but I have not tested it yet.

**Comment by kamyker** [comment]
@heshuimu good idea but I'm nor sure how well it would work so I ended up with custom unity sdk version https://github.com/PlayFab/UnitySDK/issues/217
