### ISSUE TITLE
DateTime in Events/WriteEvents API has locale-specific formatting

### ISSUE THREAD

**Issue by iouri-s** [PlayFab/UnitySDK#219]
Saw that the request was issued contained the following:
"OriginalTimestamp":"2019-11-11T21.10.14.988Z"

Note that hours, minutes and seconds are separated by a period and not by a colon.

UnitySDK version: 2.50.180906

**Comment by pgilmorepf** [comment]
At the time you posted this, you were referencing an SDK that was 14 months out-of-date for you.
Yes, we had a bug where UnitySDK was serializing dates incorrectly formatted, as you described, but that's was fixed well before your post.
If you update to a more recent SDK you'll find it has been fixed.
