### ISSUE TITLE
There is a warning exception in the console when running on android using Unity SDK.

### ISSUE THREAD

**Issue by Davidnovarro** [PlayFab/UnitySDK#220]
Playfab SDK Version: 2.77.191029
Unity Verison 2018.2
Build Settings: Net 4x IL2CPP

​Plugins: Couldn't open c, error: dlopen failed: library "c" not found

System.Net.WebRequest:Create(Uri, Boolean)
PlayFab.Internal.PlayFabWebRequest:Post(CallRequestContainer)
PlayFab.Internal.PlayFabWebRequest:WorkerThreadMainLoop()
System.Threading.ThreadHelper:ThreadStart()

**Comment by pgilmorepf** [comment]
Thank you for your bug report.
Our automated testing catches exceptions and errors, but not always warnings.
We will investigate, and leave this bug open until it's verified and/or resolved.
Thanks.

**Comment by toddbellMSFT** [comment]
@Davidnovarro are you still having this issue? If you can still reproduce this bug can you open up a post on the playfab forum? https://community.playfab.com/questions/index.html
