### ISSUE TITLE
Unity Multiplayer Server's heartbeat vanishes

### ISSUE THREAD

**Issue by MScottAdams** [PlayFab/UnitySDK#226]
Accidentally closed this issue instead of where it was refenced in the samples.

Been chasing an issue where our game server loses its heartbeat. Our server actually switches scenes during its startup.

Root cause is missing code in PlayFabMultiplayerAgentView

Adding the following to the class fixed the issue:

public class PlayFabMultiplayerAgentView : MonoBehaviour
{
private float _timer;

    /// <summary>
    /// Awake constructor
    /// </summary>
    private void Awake()
    {
        Debug.Log($"{Time.fixedTime} PlayFabMultiplayerAgentView awake ");

        // Need to keep this game object alive through scene changes.
        DontDestroyOnLoad(this);
    }

    /// <summary>
    /// Called when gameobject is destroyed
    /// </summary>
    private void OnDestroy()
    {
        Debug.Log($"{Time.fixedTime} PlayFabMultiplayerAgentView destroyed ");
    }

**Comment by dgkanatsios** [comment]
thanks for that! The gsdk repo is here https://github.com/playfab/gsdk
Since you already mitigated the issue, can you open a Pull Request over there? We'd be happy to review and discuss

**Comment by MScottAdams** [comment]
> thanks for that! The gsdk repo is here https://github.com/playfab/gsdk
> Since you already mitigated the issue, can you open a Pull Request over there? We'd be happy to review and discuss

Sorry I am a github newbie as I am more proficient  with SVN. I tried to open a pull request but was confused what came next. Do you want me to put the issue over there instead of here? 

BTW this is a Unity issue not a general gsdk. I thought this was the right repo?

**Comment by dgkanatsios** [comment]
No worries, we can help. Whereas the PlayFab Unity SDK is hosted in this repo, the Unity GSDK is hosted here -> https://github.com/PlayFab/gsdk/tree/master/UnityGsdk We use that repo for anything GSDK, including Unity GSDK. 
For guidance doing your first Pull Request, check out this README https://github.com/firstcontributions/first-contributions/blob/master/README.md

**Comment by MScottAdams** [comment]
Thank-you for the link I will read up on it.

The issue is in the Unity SDK inside the file PlayFabMultiplayerAgentView.cs and is not in the GSDK.  

Isn't this the correct place for it then?

**Comment by dgkanatsios** [comment]
The Unity SDK for all PlayFab services lives in this repo. The only exception is the Game Server SDK which lives in the GSDK repo for all languages (C#, C++, Java, Unity). Reason for that is that they are maintained and updated in a separate way. 

You mean this file? https://github.com/PlayFab/gsdk/blob/master/UnityGsdk/Assets/PlayFabSdk/MultiplayerAgent/PlayFabMultiplayerAgentView.cs

Happy to help you in the pull request, lets us know!

**Comment by MScottAdams** [comment]
Thanks that makes more sense now. 

The instructions are easy to follow for the pull. What I am lacking is the time to do it. I would greatly appreciate you taking it over from here and doing the pull request if possible.

Thank-you.

**Comment by dgkanatsios** [comment]
Thanks, of course. Can you at least open the issue on the GSDK repo so we can better track it?

**Comment by MScottAdams** [comment]
Will do!

**Comment by MScottAdams** [comment]
I am closing this issue here and reopened it as https://github.com/PlayFab/gsdk/issues/49
