### ISSUE TITLE
Add package.json for new UPM support

### ISSUE THREAD

**Issue by kamyker** [PlayFab/UnitySDK#231]
Recently Unity added relative github paths support for package manager. This means that sdk could be installed simply using: https://github.com/Cysharp/UniTask.git?path=ExampleTestProject/Assets/PlayFabSDK

Unity announcement: https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/#post-5425311

Only requirement is to add package.json file.

Example other repo using it: https://github.com/Cysharp/UniTask/tree/master/Assets/UniRx.Async
Their package.json: https://github.com/Cysharp/UniTask/blob/master/Assets/UniRx.Async/package.json

Same thing for editor extensions.

**Comment by toddbellMSFT** [comment]
The SDK team has been made aware of the feature request. Thank you for the feedback.
