### ISSUE TITLE
Annoying warning when making requests on Unity 2020.1.0b8

### ISSUE THREAD

**Issue by cgascons** [PlayFab/UnitySDK#232]
Hi,
It's just a warning, but it's a bit annoying, we believe it basically happens every time you make an API call, this is the stack trace:

**The header Accept-Encoding is managed automatically, setting it may have no effect or result in unexpected behavior.**
UnityEngine.Networking.UnityWebRequest:SetRequestHeader(String, String)
PlayFab.Internal.<Post>d__12:MoveNext() (at Assets/Plugins/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabUnityHttp.cs:139)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
PlayFab.Internal.PlayFabUnityHttp:MakeApiCall(Object) (at Assets/Plugins/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabUnityHttp.cs:119)
PlayFab.Internal.PlayFabHttp:_MakeApiCall(String, String, PlayFabRequestCommon, AuthType, Action`1, Action`1, Object, Dictionary`2, Boolean, PlayFabAuthenticationContext, PlayFabApiSettings, IPlayFabInstanceApi) (at Assets/Plugins/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:228)
PlayFab.Internal.PlayFabHttp:MakeApiCall(String, PlayFabRequestCommon, AuthType, Action`1, Action`1, Object, Dictionary`2, PlayFabAuthenticationContext, PlayFabApiSettings, IPlayFabInstanceApi) (at Assets/Plugins/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:133)
PlayFab.PlayFabEventsInstanceAPI:WriteEvents(WriteEventsRequest, Action`1, Action`1, Object, Dictionary`2) (at Assets/Plugins/PlayFabSDK/Events/PlayFabEventsInstanceAPI.cs:63)
PlayFab.Public.ScreenTimeTracker:Send() (at Assets/Plugins/PlayFabSDK/Entity/ScreenTimeTracker.cs:181)
PlayFab.Internal.<SendScreenTimeEvents>d__17:MoveNext() (at Assets/Plugins/PlayFabSDK/Shared/Internal/PlayFabHttp/PlayFabHTTP.cs:101)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Thanks for looking into it,

**Comment by toddbellMSFT** [comment]
@cgascons The SDK team has logged the bug.

I would recommend opening an issue in the forum https://community.playfab.com/questions/index.html if you haven't already. It will give you a quicker turn around time.

**Comment by cgascons** [comment]
Just did that @toddbellMSFT, thanks. Leaving [here](https://community.playfab.com/questions/44089/annoying-warning-when-making-requests-on-unity-202.html) the forum question for anyone interested in the future.
