### ISSUE TITLE
Readme: DeveloperSecret example is broken

### ISSUE THREAD

**Issue by mikelovesrobots** [PlayFab/UnitySDK#33]
In the README, there's a configuration step:

```
PlayFabSettings.DeveloperSecret = "2ksd93skd8390239s"; //your Developer Secret goes here.
```

This example is broken in a few ways:

1. In the README, this field is called `PlayFabSettings.DeveloperSecret`
2. In the PlayFab credentials page, it's actually called `PlayFab API Secret Key`
3. But in the code for the class, it's called `PlayFabSettings.DeveloperSecretKey`
4. When trying to figure out which value to copy over I noticed that the sample value "2ksd..." looks a whole lot (in length) to the Developer Id on the website.  But the actual value length for the secret key is 50 chars.

**Comment by MarcoWilliamsPF** [comment]
Thanks Mike.   This is a typo in the documentation of the README.  
You are correct however, there is a mismatch in naming convention  in the SDK and the Site.  But they are one and the same.  

PlayFab API Secret Key  = PlayFabSettings.DeveloperSecretKey

We will get the typo fixed ASAP.   Thanks for bringing this to our attention.

**Comment by zac-playfab** [comment]
Closing this out, as it appears to be fixed (removed).
