### ISSUE TITLE
Readme: crossed out instructions in the readme 

### ISSUE THREAD

**Issue by mikelovesrobots** [PlayFab/UnitySDK#34]
There's crossed out instructions in the Readme:

~~You must configure the SDK with your unique TitleId, as assigned by the PlayFab Game Manager. This value can be found in the Settings > Credentials section of the PlayFab dashboard (PlayFab website).~~

You've got source control, just remove it. You can get it back if you need it.

**Comment by zac-playfab** [comment]
Removed this section from the readme altogether.
