### ISSUE TITLE
PlayFab.Editor.PlayFabGettingStarted link broken

### ISSUE THREAD

**Issue by JohnTube** [PlayFab/UnitySDK#50]
http://developer.playfab.com/gettingstarted.html

**Comment by zac-playfab** [comment]
Hey Hamza,
Editor folder is still there:
https://github.com/PlayFab/UnitySDK/tree/master/PlayFabClientSample/Assets/PlayFabSDK/Editor

But you are right on the links, we will get this resolved. We have had some major changes with our docs and main website. Once that is settled we will get the tools updated.

Thanks for reporting!

-Zac

**Comment by pgilmorepf** [comment]
Fixed!  Thanks for the bug-report.
