### ISSUE TITLE
Login - registration flow example

### ISSUE THREAD

**Issue by Naphier** [PlayFab/UnitySDK#80]
Hello,
Your PlayFabManager example is a bit bare-boned. It would be great for new users if you provided an example for standalone as well as Android and iOS. Also it would be really great if the example contained a login-registration flow. As the example and API documentation stands there is little information on this. Some how I've been able to create 2 players on the playfab console with the same unique device id when I registered a player. Also, the example makes does not use the DeveloperSecretKey and I have been able to make calls without it (is it needed?). 
Also you make use of Dictionary() without type specifiers in the example code in the API docs. Do you mean to use System.Collections.Generic.Dictionary? Because that requires declaration of the dictionary's key and value types (i.e. new Dictionary< string,string >()). 
The product looks pretty good, it would just be helpful for newcomers if the documentation was a bit more cohesive and detailed. Otherwise we're spending too much time fumbling about trying to guess at best practices and such.
Cheers!

EDIT:
Also during the registration process is it possible to provide suggested user names since they must be unique? Or is it common that this is also set to the email address? Thanks

**Comment by MarcoWilliamsPF** [comment]
Hi Naphier, 

This example will going away very soon.  It is a very old example and we will be moving to a "plug and play" example system that has more clearly defined functionality.

However, To answer one of your questions.  DeveloperSecretKey is not needed to make Client API calls.   It is used for Server API calls only.

Thanks for your feedback and we can't wait to show you the new stuff very soon.

Marco Williams
Head of Developer Tools
PlayFab
